jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 18
    - continue-on-error: true
      name: Install dependencies
      run: 'cd site

        yarn install

        yarn build

        '
    - continue-on-error: true
      name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/build
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
        user_name: github-actions[bot]
name: Deploy to GitHub Pages
on:
  repository_dispatch:
    types: trigger-ga___deploy_docs.yml
