jobs:
  changes:
    outputs:
      legacy: ${{ steps.filter.outputs.legacy }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: .github/filters.yaml
name: Detect Changes
on:
  repository_dispatch:
    types: trigger-ga___detect_changes.yml
