jobs:
  build_JDK:
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    name: Build Java (legacy)
    needs: detect
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Piranha sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      name: Build and test using Gradle and Java
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: verGJF build
        build-root-directory: ./legacy/java
        wrapper-directory: ./legacy/java
  build_JS:
    env:
      HUSKY_SKIP_INSTALL: 1
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    name: Build JS (legacy)
    needs: detect
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - continue-on-error: true
      run: npm ci
      working-directory: legacy/javascript
    - continue-on-error: true
      run: npm test
      working-directory: legacy/javascript
    - continue-on-error: true
      run: npm test
      working-directory: legacy/javascript
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - continue-on-error: true
      name: Format
      run: 'npm ci

        npm run check_format

        '
      working-directory: legacy/javascript
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: hallee/eslint-action@1.0.3
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        source-root: legacy/javascript
  detect:
    uses: ./.github/workflows/detect_changes.yml
name: Legacy
on:
  repository_dispatch:
    types: trigger-ga___legacy.yml
