env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Polyglot Piranha Build
    needs: detect
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Piranha sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
        override: true
        profile: minimal
        toolchain: stable
    - continue-on-error: true
      name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Run pre-commit
      run: 'python -m venv .env

        source .env/bin/activate

        pip install pre-commit

        cargo install taplo-cli --locked

        pre-commit run --all-files

        '
    - continue-on-error: true
      name: Run unit and integration tests
      run: cargo build && cargo test -- --include-ignored
    - continue-on-error: true
      name: Create virtualenv and install dependencies
      run: 'python -m venv .env

        source .env/bin/activate

        pip install maturin pytest

        '
    - continue-on-error: true
      name: Run Python tests
      run: 'source .env/bin/activate

        pip install -r experimental/requirements.txt

        maturin develop

        pytest tests/tests.py

        pytest -s -rx .

        '
  detect:
    uses: ./.github/workflows/detect_changes.yml
name: Polyglot Piranha
on:
  repository_dispatch:
    types: trigger-ga___polyglot_build.yml
