jobs:
  build:
    defaults:
      run:
        working-directory: ./experimental
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - continue-on-error: true
      name: Create virtualenv and install dependencies
      run: 'python -m venv .env

        source .env/bin/activate

        pip install -r requirements.txt

        '
    - continue-on-error: true
      name: Build and check package
      run: 'source .env/bin/activate

        pip install wheel

        pip install twine

        python setup.py sdist bdist_wheel

        twine check dist/*

        twine upload --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN_PLAYGROUND
        }} dist/*

        '
name: Release Piranha Playground
on:
  repository_dispatch:
    types: trigger-ga___release_playground.yml
