jobs:
  build_and_test_legacy:
    if: ${{ needs.detect.outputs.legacy == 'false' }}
    needs: detect
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: 'echo "No changes to legacy implementations" '
  detect:
    uses: ./.github/workflows/detect_changes.yml
name: Legacy
on:
  repository_dispatch:
    types: trigger-ga___skip_legacy.yml
